import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import axios from 'axios'
import { ContactsGetModel } from '../models'
import {
  List,
  ListItem,
  ListItemButton,
  ListItemText,
  Pagination,
  Stack,
} from '@mui/material'
import { useState } from 'react'

const Home: NextPage<ContactsGetModel> = (props) => {
  const [contacts, setContacts] = useState(props.results)

  const fetchContactsPerPage = async (page: number) => {
    const data: ContactsGetModel = await axios
      .get(process.env.NEXT_PUBLIC_API! + `?page=${page}&perPage=10`)
      .then((response) => {
        return response.data
      })

    setContacts(data.results)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <nav aria-label="secondary mailbox folders">
          <List>
            {contacts.map((contact) => (
              <>
                <ListItem disablePadding>
                  <ListItemButton>
                    <ListItemText
                      primary={`${contact.firstName} ${contact.lastName}`}
                    />
                  </ListItemButton>
                </ListItem>
              </>
            ))}
          </List>
        </nav>

        <Stack spacing={2}>
          <Pagination
            count={props.totalPages}
            onChange={(e, page) => fetchContactsPerPage(page)}
          />
        </Stack>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export async function getServerSideProps() {
  const data: ContactsGetModel = await axios
    .get(process.env.NEXT_PUBLIC_API!)
    .then((response) => {
      return response.data
    })

  return {
    props: {
      count: data.count,
      perPage: data.perPage,
      currentPage: data.currentPage,
      totalPages: data.totalPages,
      results: data.results,
    },
  }
}

export default Home
